### ISSUE TITLE
Hard to find this

### ISSUE THREAD

**Issue by pmcochrane** [antwaremx/meteorman#1]
I saw your demo on the meteor impact. Wanted to try this. Google could not find it!

The name of the project clashes with a film name and google tend to break up the search into "meteor man" which doesn't find this repository.

Even if you search for antwaremx and "meteorman" it's still not really visible.

You may want to consider a name change or some other way to try and get google to recognise it if you want more users to find it.

Not really an issue as such but thought I'd let you know

Also, windows defender and symantec were not too happy about running it as it's an exe. This may be an issue on locked down enterprise PC's. I know this is not really your problem but though you should know.

**Comment by diavrank** [comment]
> You may want to consider a name change or some other way to try and get google to recognise it if you want more users to find it.

Thank you, we are going to research how to expose this repo into Google Search.

**Comment by diavrank** [comment]
Hi @pmcochrane , we published Meteorman in Electron Apps, Meteorpedia and Meteor Awesome, and it seems that now already appears in Google Search. You can try searching with:

- meteorman ddp
- meteorman github
- ddp client gui
- meteorman antwaremx

Here are some screenshot of the searchings:

![image](https://user-images.githubusercontent.com/39581375/99442320-d6692d80-28de-11eb-8063-45dbcb62251c.png)
![image](https://user-images.githubusercontent.com/39581375/99442267-c18c9a00-28de-11eb-9377-753feb432006.png)
![image](https://user-images.githubusercontent.com/39581375/99442284-c94c3e80-28de-11eb-864d-17a95ef51e53.png)
