### ISSUE TITLE
Strings in arrays of query objects turn into false

### ISSUE THREAD

**Issue by derwaldgeist** [antwaremx/meteorman#4]
If I subscribe to a subscription with this object parameter:

```
{
  "types": ["public"]
}
```

the object turns into

```
{
  "types": [false]
}
```

If there are two elements in the array:

```
{
  "types": ["groups", "public"]
}
```

this turns into:

```
{
  "types": [false, "public"]
}
```

If you try to modify the false value, the string partially re-appears.

Besides: Thanks for this great tool!

**Comment by diavrank** [comment]
Thank you @derwaldgeist for detect this issue. 

A new version of Meteorman has been released with this fix.
